Updated the zsh config.

diff --git a/zsh/.zsh/zsh-functions b/zsh/.zsh/zsh-functions
--- a/zsh/.zsh/zsh-functions
+++ b/zsh/.zsh/zsh-functions
@@ -71,3 +71,20 @@ function numowork() {
   cd ~/Git\ Projects/
   nvim
 }
+
+# Check for active Tmux session. 
+function active_tmux () {
+session="code"
+
+# Check if the session exists, discarding output
+# We can check $? for the exit status (zero for success, non-zero for failure)
+tmux has-session -t $session 2>/dev/null
+
+if [ $? != 0 ]; then
+  # Set up your session
+  tmux new-session -s code
+fi
+
+# Attach to created session
+tmux attach-session -t $session
+}
